<?php
require_once ("defs.php");

const TICKER = _TICKER;
const STAKING_ACCOUNT = _STAKING_ACCOUNT;

/**
 * RPC
 */
const RPC_HOST = _RPC_HOST;
const RPC_PORT = _RPC_PORT;
const RPC_USER = _RPC_USER;
const RPC_PASSWORD = _RPC_PASSWORD;

/**
 * Database
 */
const OLD_DB_USER = _OLD_DB_USER;
const OLD_DB_PASSWORD = _OLD_DB_PASSWORD;
const OLD_DB_HOST = _OLD_DB_HOST;

const NEW_DB_USER = _NEW_DB_USER;
const NEW_DB_PASSWORD = _NEW_DB_PASSWORD;
const NEW_DB_HOST = _NEW_DB_HOST;

/**
 * Encryption
 */
const OLD_ENCRYPTION_SALT = _OLD_ENCRYPTION_SALT;
const OLD_ENCRYPTION_EXCEPTIONS = _OLD_ENCRYPTION_EXCEPTIONS;

const NEW_ENCRYPTION_METHOD = _NEW_ENCRYPTION_METHOD;
const NEW_ENCRYPTION_SALT = _NEW_ENCRYPTION_SALT;
const NEW_ENCRYPTION_IV = _NEW_ENCRYPTION_IV;
const NEW_ENCRYPTION_EXCEPTIONS = _NEW_ENCRYPTION_EXCEPTIONS;

/**
 * Tables
 */
const USERS_TABLE = 'users';
const TRANSACTIONS_TABLE = 'transactions';
